id: P006883
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ7952
  title: སྤྱོད་འཆང་དབང་པོའི་རྣམ་ཐར་ངོ་མཚར་སྙན་པའི་སྒྲ་དབྱངས།
  author: ''
  volumes:
    77ebba73926a4197acbbe00c04ef436c:
      image_group_id: I1KG8776
      title: ''
      volume_number: 1
      total_pages: 73
      base_file: v001.txt
